name       : python-crashtest
version    : 0.3.1
release    : 1
source     :
    - https://pypi.io/packages/source/c/crashtest/crashtest-0.3.1.tar.gz : 42ca7b6ce88b6c7433e2ce47ea884e91ec93104a4b754998be498a8e6c3d37dd
license    : MIT
component  : programming.python
summary    : Manage Python errors with ease
description: |
    Manage Python errors with ease
build      : |
    %python3_setup
install    : |
    %python3_install
