name       : python-crashtest
version    : 0.4.1
release    : 2
source     :
    - https://pypi.io/packages/source/c/crashtest/crashtest-0.4.1.tar.gz : 80d7b1f316ebfbd429f648076d6275c877ba30ba48979de4191714a75266f0ce
license    : MIT
component  : programming.python
summary    : Manage Python errors with ease
description: |
    Manage Python errors with ease
build      : |
    %python3_setup
install    : |
    %python3_install
